apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myubuntu-rs
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myubuntu
      labels:
        owner: Markus
        type: myPod

    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"] 

      restartPolicy: Always
  replicas: 2
  selector:
    matchLabels:
      owner: Markus
