apiVersion: v1
kind: ReplicationController
metadata:
  name: myubuntu-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myubuntu
      labels:
        owner: Markus

    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"] 

      restartPolicy: Always
  replicas: 2
