apiVersion: v1
kind: Pod
metadata:
  name: myubuntu
  labels:
    owner: Markus

spec:
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"] 

  restartPolicy: never
# addning a comment
